zay_shop/shop/urls.py
from django.urls import path


from .views import *


urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('shop/', shop, name='shop'),
    path('category/<slug:category_slug>/', products_by_category, name='products_by_category'),
    path('sale/<slug:sale_slug>/', products_by_sale, name='products_by_sale'),
    path('gender/<slug:gender_slug>/', products_by_gender, name='products_by_gender'),
    path('brand/<slug:brand_slug>/', products_by_brand, name='products_by_brand'),
    path('ordered-name/', products_by_name, name='products_by_name'),
    path('ordered-price/', products_by_price, name='products_by_price'),
    path('contact/', contact, name='contact'),
    path('detail/<slug:product_slug>/', detail, name='detail'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('cart/', cart, name='cart'),
    path('to-cart/<int:product_id>/<str:action>', to_cart, name='to_cart'),
    path('save-review/<slug:product_slug>/', save_review, name='save_review'),
    path('payment/', create_checkout_sessions, name='payment'),
    path('success-payment/', success_payment, name='success_payment'),

]

zay_shop/zay_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zay_shop/shop/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='images/categories/')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()
    description = models.TextField()
    color = models.CharField(max_length=50)
    specification = models.TextField()
    image = models.ImageField(upload_to='images/products/')
    quantity = models.IntegerField()
    slug = models.SlugField(unique=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    size = models.ForeignKey('Size', on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, null=True)
    gender = models.ForeignKey('Gender', on_delete=models.SET_NULL, null=True, blank=True)
    sale = models.ForeignKey('Sale', on_delete=models.SET_NULL, null=True, blank=True)


class Size(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Gender(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Sale(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/brands/', null=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField(upload_to='images/products/')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User')
    photo = models.ImageField(upload_to='users/', null=True, blank=True)
    phone = models.CharField(max_length=13, verbose_name='Phone number', null=True, blank=True)
    mobile = models.CharField(max_length=13, verbose_name='Mobile', null=True, blank=True)
    email = models.EmailField(max_length=50, verbose_name='Email')
    site = models.URLField(max_length=50, null=True, blank=True)
    job = models.CharField(max_length=50, null=True, blank=True)
    job2 = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        verbose_name = 'Custom user'
        verbose_name_plural = 'Custom users'
        ordering = ['-pk']


class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    added = models.DateTimeField(auto_now_add=True, null=True)


    @property
    def get_cart_total_price(self):
        order_products = self.orderproduct_set.all()
        total_price = sum([product.get_total_price for product in order_products])
        return total_price


    @property
    def get_cart_total_quantity(self):
        order_products = self.orderproduct_set.all()
        total_quantity = len(order_products)
        return total_quantity


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    @property
    def get_total_price(self):
        total_price = self.quantity * self.product.price
        return total_price


class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150, null=True)
    email = models.EmailField(max_length=50, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    rating = models.IntegerField(default=0)

zay_shop/shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Review


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'form3Example3'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'form3Example4',
    }))


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'id': 'form3Example1c'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'id': 'form3Example3c',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'form3Example4c'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'id': 'form3Example4cd'
    }))

    class Meta:
        model = User
        fields = ['username', 'email']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['name', 'email', 'text']

zay_shop/shop/views.py
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect
from zay_shop import settings
import stripe

from django.urls import reverse
from .forms import LoginForm, RegisterForm, ReviewForm
from .models import Category, Product, Gender, Sale, Brand, Review
from .utils import CartAuthenticatedUser


# Create your views here.


def index(request):
    context = {
        'categories': Category.objects.all(),
        'products': Product.objects.order_by('-quantity')[:3],
        'brands': Brand.objects.all(),
    }
    return render(request, 'shop/index.html', context)


def about(request):
    brands = Brand.objects.all()
    return render(request, 'shop/about.html', {'brands': brands})


def shop(request):
    context = {
        'products': Product.objects.order_by('-pk'),
        'categories': Category.objects.all(),
        'genders': Gender.objects.all(),
        'sales': Sale.objects.all(),
        'brands': Brand.objects.all(),
    }
    return render(request, 'shop/shop.html', context)


def products_by_category(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    context = {
        'categories': Category.objects.all(),
        'products': Product.objects.filter(category=category),
        'genders': Gender.objects.all(),
        'sales': Sale.objects.all(),
        'brands': Brand.objects.all(),
    }
    return render(request, 'shop/shop.html', context)


def products_by_sale(request, sale_slug):
    sale = Sale.objects.get(slug=sale_slug)
    context = {
        'categories': Category.objects.all(),
        'products': Product.objects.filter(sale=sale),
        'genders': Gender.objects.all(),
        'sales': Sale.objects.all(),
        'brands': Brand.objects.all(),
    }
    return render(request, 'shop/shop.html', context)


def products_by_gender(request, gender_slug):
    gender = Gender.objects.get(slug=gender_slug)
    context = {
        'categories': Category.objects.all(),
        'products': Product.objects.filter(gender=gender),
        'genders': Gender.objects.all(),
        'sales': Sale.objects.all(),
        'brands': Brand.objects.all(),
    }
    return render(request, 'shop/shop.html', context)


def products_by_name(request):
    context = {
        'categories': Category.objects.all(),
        'products': Product.objects.order_by('name'),
        'genders': Gender.objects.all(),
        'sales': Sale.objects.all(),
        'brands': Brand.objects.all(),
    }
    return render(request, 'shop/shop.html', context)


def products_by_price(request):
    context = {
        'categories': Category.objects.all(),
        'products': Product.objects.order_by('-price'),
        'genders': Gender.objects.all(),
        'sales': Sale.objects.all(),
        'brands': Brand.objects.all(),
    }
    return render(request, 'shop/shop.html', context)


def products_by_brand(request, brand_slug):
    brands = Brand.objects.exclude(slug=None)
    brand = brands.get(slug=brand_slug)
    context = {
        'categories': Category.objects.all(),
        'products': Product.objects.filter(brand=brand),
        'genders': Gender.objects.all(),
        'sales': Sale.objects.all(),
        'brands': Brand.objects.all(),
    }
    return render(request, 'shop/shop.html', context)


def contact(request):
    return render(request, 'shop/contact.html')


def detail(request, product_slug):
    product = Product.objects.get(slug=product_slug)
    cart_info = CartAuthenticatedUser(request).get_cart_info()
    context = {
        'order_products': cart_info['order_products'],
        'cart_total_price': cart_info['cart_total_price'],
        'product': product,
        'reviews': Review.objects.filter(product=product)
    }
    return render(request, 'shop/detail.html', context)



def user_register(request):
    form = RegisterForm(data=request.POST)
    if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('index')

    form = RegisterForm()
    context = {
        'form': form,
        'title': 'Register'
    }
    return render(request, 'shop/register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')

    form = LoginForm()
    return render(request, 'shop/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('index')


def cart(request):
    if request.user.is_authenticated:
        cart_info = CartAuthenticatedUser(request).get_cart_info()
        context = {
            'order_products': cart_info['order_products'],
            'cart_total_price': cart_info['cart_total_price'],
            'page_name': 'Cart',
        }
        return render(request, 'shop/cart.html', context)
    else:
        return redirect('login')


def to_cart(request, product_id, action):
    if request.user.is_authenticated:
        CartAuthenticatedUser(request, product_id, action)
        page = request.META.get('HTTP_REFERER')
        return redirect(page)
    else:
        return redirect('login')


def save_review(request, product_slug):
    form = ReviewForm(data=request.POST)
    if request.user.is_authenticated:
        if form.is_valid():
            product = Product.objects.get(slug=product_slug)
            review = form.save(commit=False)
            review.product = product
            review.author = request.user
            review.save()
        return redirect('detail', product.slug)
    else:
        return redirect('login')


def create_checkout_sessions(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    user_cart = CartAuthenticatedUser(request)
    cart_info = user_cart.get_cart_info()
    total_price = cart_info['cart_total_price']
    total_quantity = cart_info['cart_total_quantity']

    session = stripe.checkout.Session.create(
        line_items=[{
            'price_data': {
                'currency': 'usd',
                'product_data': {
                    'name': 'Online shop items'
                },
                'unit_amount': int(total_price * 100)
            },
            'quantity': total_quantity
        }],
        mode='payment',
        success_url=request.build_absolute_uri(reverse('success_payment')),
        cancel_url=request.build_absolute_uri(reverse('success_payment')),
    )
    return redirect(session.url, 303)


def success_payment(request):
    return render(request, 'shop/success.html')

zay_shop/shop/templates/shop/about.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <section class="bg-success py-5">
        <div class="container">
            <div class="row align-items-center py-5">
                <div class="col-md-8 text-white">
                    <h1>About Us</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                </div>
                <div class="col-md-4">
                    <img src="{% static 'assets/img/about-hero.svg'%}" alt="About Hero">
                </div>
            </div>
        </div>
    </section>
    <!-- Close Banner -->

    <!-- Start Section -->
    <section class="container py-5">
        <div class="row text-center pt-5 pb-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h1">Our Services</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    Lorem ipsum dolor sit amet.
                </p>
            </div>
        </div>
        <div class="row">

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-truck fa-lg"></i></div>
                    <h2 class="h5 mt-4 text-center">Delivery Services</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fas fa-exchange-alt"></i></div>
                    <h2 class="h5 mt-4 text-center">Shipping & Return</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-percent"></i></div>
                    <h2 class="h5 mt-4 text-center">Promotion</h2>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 pb-5">
                <div class="h-100 py-5 services-icon-wap shadow">
                    <div class="h1 text-success text-center"><i class="fa fa-user"></i></div>
                    <h2 class="h5 mt-4 text-center">24 Hours Service</h2>
                </div>
            </div>
        </div>
    </section>
    <!-- End Section -->

    <!-- Start Brands -->
    <section class="bg-light py-5">
        <div class="container my-4">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Our Brands</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        Lorem ipsum dolor sit amet.
                    </p>
                </div>
                <div class="col-lg-9 m-auto tempaltemo-carousel">
                    <div class="row d-flex flex-row">
                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#templatemo-slide-brand" role="button" data-bs-slide="prev">
                                <i class="text-light fas fa-chevron-left"></i>
                            </a>
                        </div>
                        <!--End Controls-->

                        <!--Carousel Wrapper-->
                        <div class="col">
                            <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="templatemo-slide-brand"
                                 data-bs-ride="carousel">
                                <!--Slides-->
                                <div class="carousel-inner product-links-wap" role="listbox">

                                    <!--First slide-->
                                    <div class="carousel-item active">
                                        <div class="row">
                                            {% for brand in brands %}
                                                <div class="col-3 p-md-5">
                                                    <a href="{% url 'products_by_brand' brand.slug %}"><img
                                                            class="img-fluid brand-img" src="{{ brand.image.url }}"
                                                            alt="Brand Logo"></a>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <!--End First slide-->

                                    <!--Second slide-->
                                    <div class="carousel-item">
                                        <div class="row">
                                            {% for brand in brands %}
                                                <div class="col-3 p-md-5">
                                                    <a href="{% url 'products_by_brand' brand.slug %}"><img
                                                            class="img-fluid brand-img" src="{{ brand.image.url }}"
                                                            alt="Brand Logo"></a>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <!--End Second slide-->

                                    <!--Third slide-->
                                    <div class="carousel-item">
                                        <div class="row">
                                            {% for brand in brands %}
                                                <div class="col-3 p-md-5">
                                                    <a href="{% url 'products_by_brand' brand.slug %}"><img
                                                            class="img-fluid brand-img" src="{{ brand.image.url }}"
                                                            alt="Brand Logo"></a>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <!--End Third slide-->

                                </div>
                                <!--End Slides-->
                            </div>
                        </div>
                        <!--End Carousel Wrapper-->

                        <!--Controls-->
                        <div class="col-1 align-self-center">
                            <a class="h1" href="#templatemo-slide-brand" role="button" data-bs-slide="next">
                                <i class="text-light fas fa-chevron-right"></i>
                            </a>
                        </div>
                        <!--End Controls-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Brands-->
{% endblock main %}

zay_shop/shop/templates/shop/cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>To'lov amalga oshirilmadi iltimos qaytadan urinib ko'ring!</h1>
<p>Noqulayliklar uchun uzr so'raymiz</p>
<p>Operator bilan bog'lanish uchun: +998123456789</p>
<a href="{% url 'index' %}">Bosh sahifa</a>
</body>
</html>

zay_shop/shop/templates/shop/detail.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
    <!-- Open Content -->
    <section class="bg-light">
        <div class="container pb-5">
            <div class="row">
                <div class="col-lg-5 mt-5">
                    <div class="card mb-3">
                        <img class="card-img img-fluid" src="{{ product.image.url }}" alt="Card image cap"
                             id="product-detail" width="75%">
                    </div>
                    <div class="row">
                        <!--Start Controls-->
                        <div class="col-1 align-self-center">
                            <a href="#multi-item-example" role="button" data-bs-slide="prev">
                                <i class="text-dark fas fa-chevron-left"></i>
                                <span class="sr-only">Previous</span>
                            </a>
                        </div>
                        <!--End Controls-->
                        <!--Start Carousel Wrapper-->
                        <div id="multi-item-example" class="col-10 carousel slide carousel-multi-item"
                             data-bs-ride="carousel">
                            <!--Start Slides-->
                            <div class="carousel-inner product-links-wap" role="listbox">

                                <!--First slide-->
                                <div class="carousel-item active">
                                    <div class="row">
                                        {% for productimage in product.productimage_set.all %}
                                            <div class="col-4">
                                                <a href="#">
                                                    <img class="card-img img-fluid" src="{{ productimage.image.url }}"
                                                         alt="Product Image 1">
                                                </a>
                                            </div>
                                        {% endfor %}

                                    </div>
                                </div>
                                <!--/.First slide-->

                                <!--Second slide-->
                                <div class="carousel-item">
                                    <div class="row">

                                        {% for productimage in product.productimage_set.all %}
                                            <div class="col-4">
                                                <a href="#">
                                                    <img class="card-img img-fluid" src="{{ productimage.image.url }}"
                                                         alt="Product Image 1">
                                                </a>
                                            </div>
                                        {% endfor %}

                                    </div>
                                </div>
                                <!--/.Second slide-->

                            </div>
                            <!--End Slides-->
                        </div>
                        <!--End Carousel Wrapper-->
                        <!--Start Controls-->
                        <div class="col-1 align-self-center">
                            <a href="#multi-item-example" role="button" data-bs-slide="next">
                                <i class="text-dark fas fa-chevron-right"></i>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        <!--End Controls-->
                    </div>

                </div>
                <!-- col end -->
                <div class="col-lg-7 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h2">{{ product.name }}</h1>
                            <p class="h3 py-2">${{ product.price }}</p>
                            <p class="py-2">
                                <span class="list-inline-item text-dark"> 36 Comments</span>
                            </p>
                            <ul class="list-inline">
                                <li class="list-inline-item">
                                    <h6>Brand:</h6>
                                </li>
                                <li class="list-inline-item">
                                    <p class="text-muted"><strong>{{ product.brand.name }}</strong></p>
                                </li>
                            </ul>

                            <h6>Description:</h6>
                            <p>{{ product.description|linebreaks }}</p>

                            <h6>Specification:</h6>
                            <ul class="list-unstyled pb-3">
                                <li>{{ product.specification|linebreaks }}</li>
                            </ul>
                            {% if request.user.is_authenticated %}
                                <form action="{% url 'save_review' product.slug %}" method="post">
                                    {% csrf_token %}
                                    <h4 class="mb-5 fw-bold">Leave a Reply</h4>
                                    <div class="row g-4">
                                        <div class="col-lg-6">
                                            <div class="border-bottom rounded">
                                                <input name="name" type="text" class="form-control border-0 me-4"
                                                       placeholder="Yur Name *">
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <div class="border-bottom rounded">
                                                <input name="email" type="email" class="form-control border-0"
                                                       placeholder="Your Email *">
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="border-bottom rounded my-4">
                                    <textarea name="text" id="" class="form-control border-0" cols="30" rows="4"
                                              placeholder="Your Review *" spellcheck="false"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-lg-12">
                                            <div class="d-flex justify-content-between py-3 mb-5">
                                                <button type="submit"
                                                        class="btn border border-secondary text-primary rounded-pill px-4 py-3">
                                                    Post Comment
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            {% endif %}

                            <form action="" method="GET">
                                <input type="hidden" name="product-title" value="Activewear">
                                <div class="row">
                                    <div class="col-auto">
                                        <ul class="list-inline pb-3">
                                            <li class="list-inline-item">Size :
                                                <input type="hidden" name="product-size" id="product-size" value="S">
                                            </li>
                                            <li class="list-inline-item"><span
                                                    class="btn btn-success btn-size">{{ product.size.name }}</span></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="row pb-3">
                                    <div class="col d-grid">
                                        <a href="{% url 'to_cart' product.id 'add' %}" type="submit"
                                           class="btn btn-success btn-lg" value="addtocard">Add To Cart</a>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                    {% for review in reviews|slice:":3" %}
                        <div class="d-flex">
                            <div class="">
                                <p class="mb-2" style="font-size: 14px;">{{ review.added }}</p>
                                <div class="d-flex justify-content-between">
                                    <h5>{{ review.author.username }}</h5>
                                </div>
                                <p>{{ review.text|linebreaks }} </p>
                                <hr>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>




{% endblock main %}

zay_shop/shop/templates/shop/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>To'lob muvaffaqqiyatli amalga oshirildi</h1>
<a href="{% url 'index' %}">Bosh sahifa</a>
</body>
</html>